CREATE TABLE Veiculos (
    id INT PRIMARY KEY IDENTITY(1, 1),
    Placa NVARCHAR(MAX) NOT NULL,
    Marca NVARCHAR(MAX) NOT NULL,
    Modelo NVARCHAR(MAX) NOT NULL,
    Tipo NVARCHAR(MAX) NOT NULL,
    Unidade NVARCHAR(MAX) NOT NULL,
    Renavam NVARCHAR(MAX) NOT NULL,
    Ativo BIT NOT NULL,
    DataCriacao DATETIME2 NOT NULL
);
